/**
 * Controlled Genealogy & Network Constants
 * Phase 5: Genealogy & Referral Network Foundation
 */

export const PLACEMENT_POSITION = Object.freeze({
  LEFT: "left",
  RIGHT: "right",
});

export const VALID_PLACEMENT_POSITIONS = Object.freeze([
  PLACEMENT_POSITION.LEFT,
  PLACEMENT_POSITION.RIGHT,
]);

export const GENEALOGY_TREE_LIMITS = Object.freeze({
  DEFAULT_BINARY_TREE_DEPTH: 4,
  MAX_BINARY_TREE_DEPTH: 5,
  DEFAULT_SPONSOR_TREE_DEPTH: 2,
  MAX_SPONSOR_TREE_DEPTH: 5,
  MAX_DESCENDANT_DEPTH: 10,
  MAX_DESCENDANT_NODES: 500,
  HARD_SAFETY_TRAVERSAL_LIMIT: 1000,
});

export const GENEALOGY_AUDIT_ACTIONS = Object.freeze({
  MEMBER_PLACED: "GENEALOGY_MEMBER_PLACED",
  PLACEMENT_REJECTED_OCCUPIED: "GENEALOGY_PLACEMENT_REJECTED_OCCUPIED",
  CYCLE_DETECTED: "GENEALOGY_CYCLE_DETECTED",
  UNAUTHORIZED_TREE_ACCESS: "GENEALOGY_UNAUTHORIZED_TREE_ACCESS",
  INTEGRITY_MISMATCH: "GENEALOGY_INTEGRITY_MISMATCH",
});
