/**
 * Green Future Tech (GFT) — Authoritative Ledger Constants
 * Phase 4: Controlled constants for double-entry ledger, accounts, and events.
 */

export const JOURNAL_STATUS = Object.freeze({
  PENDING: "PENDING",
  COMMITTED: "COMMITTED",
  FAILED: "FAILED",
  REJECTED_INSUFFICIENT_FUNDS: "REJECTED_INSUFFICIENT_FUNDS",
  CORRUPT_IMBALANCED: "CORRUPT_IMBALANCED",
  FAILED_ABORTED: "FAILED_ABORTED",
  COMMITTED_BY_RECONCILIATION: "COMMITTED_BY_RECONCILIATION",
});

export const POSTING_DIRECTION = Object.freeze({
  DEBIT: "DEBIT",
  CREDIT: "CREDIT",
});

export const ACCOUNT_TYPES = Object.freeze({
  USER_AVAILABLE: "USER_AVAILABLE",
  USER_LOCKED: "USER_LOCKED",
  SYSTEM_CLEARING: "SYSTEM_CLEARING",
  SYSTEM_RESERVE: "SYSTEM_RESERVE",
  SYSTEM_WITHDRAWAL_HOLD: "SYSTEM_WITHDRAWAL_HOLD",
  SYSTEM_SUSPENSE: "SYSTEM_SUSPENSE",
  SYSTEM_ADJUSTMENTS: "SYSTEM_ADJUSTMENTS",
});

export const JOURNAL_EVENT_TYPES = Object.freeze({
  MANUAL_DEPOSIT: "MANUAL_DEPOSIT",
  ORDER_PAYMENT: "ORDER_PAYMENT",
  COMMISSION_CREDIT: "COMMISSION_CREDIT",
  WITHDRAWAL_HOLD: "WITHDRAWAL_HOLD",
  WITHDRAWAL_SETTLED: "WITHDRAWAL_SETTLED",
  REVERSAL: "REVERSAL",
  ADMIN_ADJUSTMENT: "ADMIN_ADJUSTMENT",
  SYSTEM_CORRECTION: "SYSTEM_CORRECTION",
});

export const SUPPORTED_LEDGER_CURRENCIES = Object.freeze(["INR", "USDT", "GFT"]);

/**
 * GFT Token precision placeholder: strictly unconfirmed.
 */
export const TOKEN_PRECISION = "REQUIRES_CLIENT_CONFIRMATION";
