/**
 * Green Future Tech (GFT) — Authoritative Withdrawal Constants
 * Phase 8: Safe Withdrawal & Payout Engine
 */

export const WITHDRAWAL_STATUS = Object.freeze({
  REQUESTED: "REQUESTED",
  UNDER_REVIEW: "UNDER_REVIEW",
  APPROVED: "APPROVED",
  PROCESSING: "PROCESSING",
  COMPLETED: "COMPLETED",
  REJECTED: "REJECTED",
  FAILED: "FAILED",
});

export const DESTINATION_TYPES = Object.freeze({
  BANK_TRANSFER: "BANK_TRANSFER",
  USDT_TRC20: "USDT_TRC20",
  USDT_BEP20: "USDT_BEP20",
});

export const ALLOWED_STATE_TRANSITIONS = Object.freeze({
  [WITHDRAWAL_STATUS.REQUESTED]: [
    WITHDRAWAL_STATUS.UNDER_REVIEW,
    WITHDRAWAL_STATUS.REJECTED,
  ],
  [WITHDRAWAL_STATUS.UNDER_REVIEW]: [
    WITHDRAWAL_STATUS.APPROVED,
    WITHDRAWAL_STATUS.REJECTED,
  ],
  [WITHDRAWAL_STATUS.APPROVED]: [
    WITHDRAWAL_STATUS.PROCESSING,
    WITHDRAWAL_STATUS.FAILED,
  ],
  [WITHDRAWAL_STATUS.PROCESSING]: [
    WITHDRAWAL_STATUS.COMPLETED,
    WITHDRAWAL_STATUS.FAILED,
  ],
  [WITHDRAWAL_STATUS.COMPLETED]: [],
  [WITHDRAWAL_STATUS.REJECTED]: [],
  [WITHDRAWAL_STATUS.FAILED]: [],
});

export const WITHDRAWAL_AUDIT_ACTIONS = Object.freeze({
  WITHDRAWAL_REQUESTED: "WITHDRAWAL_REQUESTED",
  WITHDRAWAL_BLOCKED: "WITHDRAWAL_BLOCKED",
  WITHDRAWAL_REVIEW_STARTED: "WITHDRAWAL_REVIEW_STARTED",
  WITHDRAWAL_APPROVED: "WITHDRAWAL_APPROVED",
  WITHDRAWAL_REJECTED: "WITHDRAWAL_REJECTED",
  WITHDRAWAL_PROCESSING: "WITHDRAWAL_PROCESSING",
  WITHDRAWAL_COMPLETED: "WITHDRAWAL_COMPLETED",
  WITHDRAWAL_FAILED: "WITHDRAWAL_FAILED",
  WITHDRAWAL_DUPLICATE: "WITHDRAWAL_DUPLICATE",
  WITHDRAWAL_REVERSED: "WITHDRAWAL_REVERSED",
  WITHDRAWAL_RECONCILIATION_MISMATCH: "WITHDRAWAL_RECONCILIATION_MISMATCH",
});
